version: "3.9"

services:
  db:
    image: mysql:8.0.44
    container_name: fantasy_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"   # Elegir un puerto que no esté en uso en tu caso
    volumes:
      - db_data:/var/lib/mysql
      - ./demo_data.sql:/docker-entrypoint-initdb.d/demo_data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: fantasy_app
    restart: always
    env_file: .env
    ports:
      - "8080:8080" # Elegir un puerto que no esté en uso en tu caso
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  db_data:
